# Generated by Django 5.0.6 on 2024-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=254, null=True, upload_to="posts/images/"
                    ),
                ),
            ],
        ),
    ]
