# Generated by Django 5.0.6 on 2024-06-04 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
