# Generated by Django 5.0.6 on 2024-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_remove_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, max_length=254, null=True, upload_to="posts/images/"
            ),
        ),
    ]
