# Generated by Django 5.0.6 on 2024-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0004_post_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                db_index=True,
                default="167a714dea0c42a4a410a3aeac354b14",
                editable=False,
                max_length=128,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
