# Generated by Django 5.0.6 on 2024-06-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default="0500f5d792d943eb9f43c92754c236f7",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
