apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway_service_image:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: gateway_service.settings
        - name: USER_SERVICE_URL
          value: http://user-service:8000
        - name: FEEDS_SERVICE_URL
          value: http://feeds-service:8000
        - name: RDS_NAME
          value: postgres
        - name: RDS_USER
          value: postgres
        - name: RDS_PASSWORD
          value: postgres
        - name: RDS_HOST
          value: db
        - name: RDS_PORT
          value: "5432"
    dependsOn:
      - user
      - notification
      - feeds

