apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user_service_image:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: user_service.settings
        - name: RDS_NAME
          value: postgres
        - name: RDS_USER
          value: postgres
        - name: RDS_PASSWORD
          value: postgres
        - name: RDS_HOST
          value: db
        - name: RDS_PORT
          value: "5432"
