# Generated by Django 5.0.6 on 2024-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_channel",
            field=models.CharField(
                blank=True,
                choices=[("sms", "Sms"), ("email", "Email")],
                default="email",
                max_length=1500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                db_index=True,
                default="43efac6a23e848d1aa5dafa8baf0a0de",
                editable=False,
                max_length=128,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
